city_data_dict = {
    "Fremont": {
        "Average Spring Temperature (Fahrenheit)": 70.5,
        "Average Spring Rainfall (inches)": 3.8,
    },
    "San Jose": {
        "Average Spring Temperature (Fahrenheit)": 73.2,
        "Average Spring Rainfall (inches)": 3.5,
    },
    "Los Altos": {
        "Average Spring Temperature (Fahrenheit)": 71.9,
        "Average Spring Rainfall (inches)": 4.7,
    },
    "Palo Alto": {
        "Average Spring Temperature (Fahrenheit)": 74.8,
        "Average Spring Rainfall (inches)": 2.5,
    },
    "Oakland": {
        "Average Spring Temperature (Fahrenheit)": 69.6,
        "Average Spring Rainfall (inches)": 5.9,
    },
}
crop_data_dict = {
    "Wheat": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Barley": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 70.0},
    "Oats": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 68.0},
    "Rye": {"Necessary Rainfall (inches)": 7.5, "Necessary Average Temperature (Fahrenheit)": 65.0},
    "Maize": {"Necessary Rainfall (inches)": 12.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Rice": {"Necessary Rainfall (inches)": 15.0, "Necessary Average Temperature (Fahrenheit)": 85.0},
    "Sorghum": {"Necessary Rainfall (inches)": 8.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Millet": {"Necessary Rainfall (inches)": 7.0, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Quinoa": {"Necessary Rainfall (inches)": 10.5, "Necessary Average Temperature (Fahrenheit)": 72.0},
    "Amaranth": {"Necessary Rainfall (inches)": 9.5, "Necessary Average Temperature (Fahrenheit)": 70.0},
    "Teff": {"Necessary Rainfall (inches)": 8.0, "Necessary Average Temperature (Fahrenheit)": 68.0},
    "Spelt": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 72.0},
    "Einkorn": {"Necessary Rainfall (inches)": 7.0, "Necessary Average Temperature (Fahrenheit)": 68.0},
    "Emmer": {"Necessary Rainfall (inches)": 7.5, "Necessary Average Temperature (Fahrenheit)": 70.0},
    "Khorasan": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Buckwheat": {"Necessary Rainfall (inches)": 7.0, "Necessary Average Temperature (Fahrenheit)": 68.0},
    "Soybeans": {"Necessary Rainfall (inches)": 11.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Lentils": {"Necessary Rainfall (inches)": 8.0, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Chickpeas": {"Necessary Rainfall (inches)": 9.5, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Black-eyed Peas": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Kidney Beans": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Pinto Beans": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Adzuki Beans": {"Necessary Rainfall (inches)": 8.0, "Necessary Average Temperature (Fahrenheit)": 72.0},
    "Lima Beans": {"Necessary Rainfall (inches)": 9.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Garbanzo Beans": {"Necessary Rainfall (inches)": 10.5, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Fava Beans": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Sunflower Seeds": {"Necessary Rainfall (inches)": 11.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Pumpkin Seeds": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Flaxseeds": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Chia Seeds": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Hemp Seeds": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Poppy Seeds": {"Necessary Rainfall (inches)": 8.0, "Necessary Average Temperature (Fahrenheit)": 72.0},
    "Sesame Seeds": {"Necessary Rainfall (inches)": 9.5, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Mustard Seeds": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Cumin Seeds": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Coriander Seeds": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Fennel Seeds": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Caraway Seeds": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Anise Seeds": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Safflower Seeds": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Agricultural Hemp": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Canola": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Cotton Seeds": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Peanuts": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Walnuts": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Almonds": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Cashews": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Pistachios": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Hazelnuts": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Pecans": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Brazil Nuts": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Macadamia Nuts": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Chestnuts": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Cocoa Beans": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Coffee Beans": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
    "Flax": {"Necessary Rainfall (inches)": 8.5, "Necessary Average Temperature (Fahrenheit)": 75.0},
    "Hemp": {"Necessary Rainfall (inches)": 9.0, "Necessary Average Temperature (Fahrenheit)": 78.0},
    "Chia": {"Necessary Rainfall (inches)": 10.0, "Necessary Average Temperature (Fahrenheit)": 80.0},
}
